[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Netlify-CDN-Cache-Control = "no-store"
    Surrogate-Control = "no-store"
    Pragma = "no-cache"
